### ISSUE TITLE
Stripe Error

### ISSUE THREAD

**Issue by azoff** [omniprojects/omni-stripe-php-client#1]
another stripe error in the logs:

```
[2015-07-15 21:53:10] production.ERROR: exception 'Stripe_InvalidRequestError' with message 'Received unknown parameter: 0' in /var/www/api.beomni.com/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php:147
Stack trace:
#0 /var/www/api.beomni.com/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php(268): Stripe_ApiRequestor->handleApiError('{\n  "error": {\n...', 400, Array)
#1 /var/www/api.beomni.com/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php(109): Stripe_ApiRequestor->_interpretResponse('{\n  "error": {\n...', 400)
#2 /var/www/api.beomni.com/vendor/stripe/stripe-php/lib/Stripe/ApiResource.php(143): Stripe_ApiRequestor->request('post', '/v1/customers', Array, Array)
#3 /var/www/api.beomni.com/vendor/stripe/stripe-php/lib/Stripe/Customer.php(38): Stripe_ApiResource::_scopedCreate('Stripe_Customer', Array, NULL)
#4 /var/www/api.beomni.com/vendor/omni/stripe/src/StripeProxy.php(39): Stripe_Customer::create(Array)
#5 /var/www/api.beomni.com/vendor/omni/stripe/src/StripeProxy.php(87): Omni\Stripe\StripeProxy->updateCustomer(NULL, Array)
#6 /var/www/api.beomni.com/vendor/omni/api-v1/src/models/User.php(573): Omni\Stripe\StripeProxy->updateUser(NULL, Array)
#7 /var/www/api.beomni.com/vendor/omni/api-v1/src/models/User.php(549): Omni\ApiV1\User->updateStripeUser(NULL, Array)
#8 /var/www/api.beomni.com/vendor/omni/api-v1/src/controllers/ProfileController.php(201): Omni\ApiV1\User->update(Array)
#9 [internal function]: Omni\ApiV1\ProfileController->updateUser()
#10 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#11 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('updateUser', Array)
#12 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Omni\ApiV1\ProfileController), Object(Illuminate\Routing\Route), 'updateUser')
#13 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Omni\\ApiV1\\Prof...', 'updateUser')
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#16 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/api.beomni.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/api.beomni.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/api.beomni.com/public/index.php(54): Illuminate\Foundation\Application->run()
#26 {main} [] []
```

**Comment by dmitrymomot** [comment]
@azoff, It happens when stripe id is not provided by salesforce

**Comment by mkorabel** [comment]
since there is no information related to particular salesforce record I'd like to close this issue

**Comment by azoff** [comment]
can we at least log this error without crashing?

**Comment by dmitrymomot** [comment]
API is not endpoint in this flow and it returns you truthful data about current operation. You have to handle this error on website.

**Comment by mkorabel** [comment]
The case here is that account that is being updated does not have stripe_id within salesforce profile, that's why we have this error. Since we don't now which account is affected we can't investigate it further but my assumption would be that it's related to one of our test accounts.
